### ISSUE TITLE
Suggestion: sign release tarball

### ISSUE THREAD

**Issue by lyknode** [grazzolini/chkboot#14]
Dear maintainer,

It would be really nice if you added cryptographic signature for future releases. I see that you already have a GPG key and I think it would be nice for users that want to check that sources distributed match the actual release could do so.

This is a purely "bonus" suggestion. Please feel free to close this issue if you do not wish to add the signature :)

Best,

https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by grazzolini** [comment]
@lyknode as soon as we are done with the pending PR's, I'll release a new version and will sign the tarball. On addition, all my commits are signed as well.

**Comment by lyknode** [comment]
Very nice!
I should be able to attend to the last PR in the next couple of hours.

**Comment by lyknode** [comment]
(Don't forget to sign the tarball ;))
