### ISSUE TITLE
Running chkboot twice in same minute causes broken links

### ISSUE THREAD

**Issue by giddie** [grazzolini/chkboot#5]
When running chkboot twice in quick succession, the two runs generate checksums in a file with the same name (ending in YYMMDD-HHmm). After the second run, the checksum file has been deleted, and BOOTFILES-last and DISKHEAD-last are broken links.

Presumably, this is because the second run uses the same filename as the previous run.

**Comment by grazzolini** [comment]
@giddie
I was able to reproduce your issue. It happens because of the way the filenames are constructed. If you run two chkboot commands at the same minute, then the issue arises. I'll look into how to fix this.

Just curious, why you're running two commands in such quick succession?

**Comment by giddie** [comment]
I came to the same conclusion :) I did it simply to test the detection of changes in /boot. I'd run `chkboot`, make a modification, then run it again to see if it would detect the change. I got really confused about the behaviour before I figured eventually figuring out what was happening :D

**Comment by grazzolini** [comment]
@giddie 
The correct way to check for changes is to run chkboot first then run chkboot-check. It warns you if there is any change since your last chkboot run.

Anyway, this is a bug that's easily fixable, so I'm working on it at this moment.

**Comment by giddie** [comment]
Well, that script outputs the warning, but if I understand correctly, it doesn't actually perform the check itself. It relies on a previous run of chkboot. So in order for chkboot-check to output anything, we need the sequence:

chkboot [-u]
>> make changes <<
chkboot
chkboot-check

**Comment by grazzolini** [comment]
@giddie 
It depends on just one successful run of chkboot. The flux really is just chkboot, then, chkboot-check. You can confirm this behaviour by creating a file under /boot, then running chkboot and chkboot-check.

chkboot -u is meant to remove any warning message that might be there so, it should only be run after valid changes to /boot (ie. new kernel installs, bootloader changes, etc). I plan to add a pacman hook to chkboot so it is triggered _after_ kernel installs. The way it works now by running last in the mkinitcpio build isn't the best way to accomplish this. Anyway, I think I might introduce the seconds in the filename so, consecutive runs of chkboot within the same minute won't matter. Another option would be a lock file.
